"""add chunk metadata

Revision ID: 5ce9d8f67210
Revises: fcdf1ac998bc
Create Date: 2026-09-14 12:15:41.382213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ce9d8f67210'
down_revision: Union[str, Sequence[str], None] = 'fcdf1ac998bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('chunk_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'chunk_metadata')
    # ### end Alembic commands ###
