"""add embedding status

Revision ID: dc8bcb807528
Revises: 5ce9d8f67210
Create Date: 2026-09-18 23:30:15.705540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc8bcb807528'
down_revision: Union[str, Sequence[str], None] = '5ce9d8f67210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "document_chunks",
        sa.Column(
            "embedding_status",
            sa.String(length=20),
            nullable=True,
        ),
    )

    op.execute(
        "UPDATE document_chunks "
        "SET embedding_status = 'pending' "
        "WHERE embedding_status IS NULL"
    )

    op.alter_column(
        "document_chunks",
        "embedding_status",
        nullable=False,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'embedding_status')
    # ### end Alembic commands ###
