"""add document type

Revision ID: e82091ecd9ce
Revises: dc8bcb807528
Create Date: 2026-09-22 11:06:11.481827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e82091ecd9ce'
down_revision: Union[str, Sequence[str], None] = 'dc8bcb807528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # 1. 先允许 NULL，避免已有文档无法添加字段
    op.add_column(
        "documents",
        sa.Column(
            "document_type",
            sa.String(length=20),
            nullable=True,
        ),
    )

    # 2. 历史文档暂时归类为 other
    op.execute(
        "UPDATE documents "
        "SET document_type = 'other' "
        "WHERE document_type IS NULL"
    )

    # 3. 再改成 NOT NULL
    op.alter_column(
        "documents",
        "document_type",
        existing_type=sa.String(length=20),
        nullable=False,
    )

    # 4. 创建索引
    op.create_index(
        op.f("ix_documents_document_type"),
        "documents",
        ["document_type"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_column('documents', 'document_type')
    # ### end Alembic commands ###
